name: kyverno-policy-test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Kyverno CLI
        uses: kyverno/action-install-cli@v0.2.0
        with:
          release: 'v1.13.6'
      - name: Check install
        run: kyverno version
      - name: Test pre-defined cases
        run: kyverno test tests/
